# Generated by Django 3.1 on 2020-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('number', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(default='all', max_length=15)),
                ('correct_answers', models.TextField(default='')),
                ('question', models.TextField(default='text')),
                ('material', models.FileField(blank=True, upload_to='')),
                ('type', models.IntegerField(default=0)),
                ('hint', models.TextField()),
                ('hint_price', models.IntegerField(default=5)),
                ('points', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='player', max_length=30, unique=True)),
                ('key', models.CharField(default='teamkey', max_length=8, unique=True)),
                ('password', models.CharField(default='', max_length=8, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('captain', models.CharField(default='vk.com/', max_length=30, unique=True)),
                ('participants', models.IntegerField(default=1)),
                ('time_of_begin', models.TimeField(default='10:00')),
            ],
        ),
    ]
